services:
  mongo_ball:
    platform: linux/arm64/v8
    privileged: true
    tty: true
    restart: unless-stopped
    image: mongo:4.4.18
    network_mode: "bridge"
    environment:
      MONGO_INITDB_ROOT_USERNAME: basketball
      MONGO_INITDB_ROOT_PASSWORD: basketball
      MONGO_INITDB_DATABASE: basketball
    ports:
      - "37017:27017"
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - mongo_ball:/data/db

volumes:
  mongo_ball:
